### PR TITLE
Fix getTotalCount()

### PR DESCRIPTION
**Pull request by aspoky**
Adding a forgotten `async` in the `getTotalCount` function.

### CODE REVIEW

**Comment by aspoky** [comment]
Check this pull request out
@solocommand @zarathustra323

**Review by solocommand — COMMENTED** [review]
@Aspoky thanks for the contribution! However, I’m not sure what effect you’re expecting here. Since the run function itself returns a promise, and it doesn’t need to await anything inside, adding the async decorator seems unnecessary. Are you running into a problem using the package?

**Comment by aspoky** [comment]
> @Aspoky thanks for the contribution! However, I’m not sure what effect you’re expecting here. Since the run function itself returns a promise, and it doesn’t need to await anything inside, adding the async decorator seems unnecessary. Are you running into a problem using the package?

@solocommand Yeah, when you attempt querying `totalCount` on your GraphQL request, you can see a `Query already executed` error, hence this modification was made to fix this problem. Also if you take a look at the rest of `run` arrow functions from the pagination file, all of them are asynchronous except the `getTotalCount` one

**Comment by aspoky** [comment]
@solocommand

**Pull request closed without merging**
